// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Shiva_Enterprise_APIs.Entities.Purchase;

namespace Shiva_Enterprise_APIs.Entities;

[Table("City")]
public partial class City
{
    [Key]
    public Guid CityId { get; set; }

    public string City_Code { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string City_Name { get; set; }

    public Guid? State_Id { get; set; }

    public bool IsActive { get; set; }
    public string CreatedBy { get; set; }
    public DateTime CreatedDateTime { get; set; }
    public string? ModifiedBy { get; set; }
    public DateTime? ModifiedDateTime { get; set; }

    [ForeignKey("State_Id")]
    [InverseProperty("Cities")]
    public virtual State State { get; set; }

    [InverseProperty("City")]
    public virtual ICollection<Vendor> VendorCity { get; set; } = new List<Vendor>();

    [InverseProperty("City")]
    public virtual ICollection<Customer> Customer { get; set; } = new List<Customer>();

}