// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shiva_Enterprise_APIs.Entities;

[Table("Country")]
public partial class Country
{
    [Key]
    public Guid Country_ID { get; set; }

    [StringLength(200)]
    public string Country_Name { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Country_Code { get; set; }
    public string CreatedBy { get; set; }
    public DateTime CreatedDateTime { get; set; }
    public string? ModifiedBy { get; set; }
    public DateTime? ModifiedDateTime { get; set; }

    [InverseProperty("Country")]
    public virtual ICollection<state> states { get; set; } = new List<state>();
}