// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shiva_Enterprise_APIs.Entities;

[Table("state")]
public partial class State
{
    [Key]
    public Guid State_Id { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string State_Name { get; set; }
    public string State_Code { get; set; }
    public Guid? Country_Id { get; set; }
    public bool IsActive { get; set; }
    public string CreatedBy { get; set; }
    public DateTime CreatedDateTime { get; set; }
    public string? ModifiedBy { get; set; }
    public DateTime? ModifiedDateTime { get; set; }

    [InverseProperty("State")]
    public virtual ICollection<City> Cities { get; set; } = new List<City>();

    [ForeignKey("Country_Id")]
    [InverseProperty("states")]
    public virtual Country Country { get; set; }
}