// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shiva_Enterprise_APIs.Models;

[Table("Branch")]
[Index("Company_Id", Name = "IX_Branch_Company_Id")]
public partial class Branch
{
    [Key]
    public Guid Branch_Id { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string Branch_Code { get; set; } = null!;

    [StringLength(200)]
    [Unicode(false)]
    public string Branch_Name { get; set; } = null!;

    public Guid? Company_Id { get; set; }

    public bool IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedDateTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedDateTime { get; set; }

    [ForeignKey("Company_Id")]
    [InverseProperty("Branches")]
    public virtual Company? Company { get; set; }
}