// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shiva_Enterprise_APIs.Models;

[Table("Company")]
public partial class Company
{
    [Key]
    public Guid Company_Id { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string Company_Code { get; set; } = null!;

    [StringLength(200)]
    [Unicode(false)]
    public string Company_Name { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime? Company_Startyear { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Company_Endyear { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDateTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedDateTime { get; set; }

    public bool? IsActive { get; set; }

    [InverseProperty("Company")]
    public virtual ICollection<Branch> Branches { get; set; } = new List<Branch>();
}