// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shiva_Enterprise_APIs.Models;

[Table("Role")]
public partial class Role
{
    [Key]
    public Guid RoleID { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string? Role_Name { get; set; }

    public bool? IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDateAndTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedDateAndTime { get; set; }

    [InverseProperty("Role")]
    public virtual ICollection<RoleMembership> RoleMemberships { get; set; } = new List<RoleMembership>();
}