// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shiva_Enterprise_APIs.Models;

[Table("RoleMembership")]
[Index("RoleID", Name = "IX_RoleMembership_RoleID")]
[Index("UserID", Name = "IX_RoleMembership_UserID")]
public partial class RoleMembership
{
    [Key]
    public Guid RoleMenmbershiID { get; set; }

    public Guid? RoleID { get; set; }

    public string? UserID { get; set; }

    [ForeignKey("RoleID")]
    [InverseProperty("RoleMemberships")]
    public virtual Role? Role { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("RoleMemberships")]
    public virtual AspNetUser? User { get; set; }
}