// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Shiva_Enterprise_APIs.Models.Configurations;
using System;
using System.Collections.Generic;
#nullable enable

namespace Shiva_Enterprise_APIs.Models;

public partial class ShivaEnterpriseContext : DbContext
{
    public ShivaEnterpriseContext()
    {
    }

    public ShivaEnterpriseContext(DbContextOptions<ShivaEnterpriseContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AspNetRole> AspNetRoles { get; set; }

    public virtual DbSet<AspNetRoleClaim> AspNetRoleClaims { get; set; }

    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }

    public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }

    public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }

    public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }

    public virtual DbSet<AspNetUserToken> AspNetUserTokens { get; set; }

    public virtual DbSet<Branch> Branches { get; set; }

    public virtual DbSet<City> Cities { get; set; }

    public virtual DbSet<Company> Companies { get; set; }

    public virtual DbSet<Country> Countries { get; set; }

    public virtual DbSet<IdentityUserClaim> IdentityUserClaims { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<RoleMembership> RoleMemberships { get; set; }

    public virtual DbSet<location> locations { get; set; }

    public virtual DbSet<salesmanAgent> salesmanAgents { get; set; }

    public virtual DbSet<state> states { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=LAPTOP-DRBPPARM\\MSSQLSERVER2;Initial Catalog=ShivaEnterprise;Persist Security Info=True;User ID=sa;Password=Ps@1234;Encrypt=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.AspNetRoleConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.AspNetUserConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.BranchConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CityConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CompanyConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CountryConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.RoleConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.RoleMembershipConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.locationConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.salesmanAgentConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.stateConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
