// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shiva_Enterprise_APIs.Models;

[Table("state")]
[Index("Country_ID", Name = "IX_state_Country_ID")]
public partial class state
{
    [Key]
    public Guid State_ID { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string? State_Name { get; set; }

    public Guid? Country_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDateAndTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedDateAndTime { get; set; }

    [InverseProperty("State")]
    public virtual ICollection<City> Cities { get; set; } = new List<City>();

    [ForeignKey("Country_ID")]
    [InverseProperty("states")]
    public virtual Country? Country { get; set; }
}