// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Shiva_Enterprise_APIs.Entities;

[Table("Branch")]
public partial class Branch
{
    [Key]
    public Guid Branch_Id { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string Branch_Code { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string Branch_Name { get; set; }

    public Guid? Company_Id { get; set; }

    public bool IsActive { get; set; }

    public string CreatedBy { get; set; }
    public DateTime CreatedDateTime { get; set; }
    public string? ModifiedBy { get; set; }
    public DateTime? ModifiedDateTime { get; set; }

    [ForeignKey("Company_Id")]
    [InverseProperty("Branches")]
    public virtual Company Company { get; set; }
}