// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shiva_Enterprise_APIs.Entities;

[Table("City")]
public partial class City
{
    [Key]
    public Guid City_ID { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string CityName { get; set; }

    public Guid? State_id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDateAndTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedDateAndTime { get; set; }

    [ForeignKey("State_id")]
    [InverseProperty("Cities")]
    public virtual state State { get; set; }
}