// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Shiva_Enterprise_APIs.Entities.Authentication;

namespace Shiva_Enterprise_APIs.Entities;

[Table("RoleMembership")]
public partial class RoleMembership
{
    [Key]
    public Guid RoleMenmbershiID { get; set; }

    public Guid? RoleID { get; set; }

    public string? UserID { get; set; }

    [ForeignKey("RoleID")]
    [InverseProperty("RoleMemberships")]
    public virtual Role Role { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("RoleMemberships")]
    public virtual ApplicationUser User { get; set; }
}