// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Shiva_Enterprise_APIs.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Shiva_Enterprise_APIs.Models.Configurations
{
    public partial class CityConfiguration : IEntityTypeConfiguration<City>
    {
        public void Configure(EntityTypeBuilder<City> entity)
        {
            entity.HasKey(e => e.City_ID).HasName("PK__city__DE9DE0205736F02F");

            entity.Property(e => e.City_ID).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedDateAndTime).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.State).WithMany(p => p.Cities).HasConstraintName("FK_City_state");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<City> entity);
    }
}
