// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Shiva_Enterprise_APIs.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Shiva_Enterprise_APIs.Models.Configurations
{
    public partial class locationConfiguration : IEntityTypeConfiguration<location>
    {
        public void Configure(EntityTypeBuilder<location> entity)
        {
            entity.HasKey(e => e.Location_ID).HasName("PK__location__D2BA00C2438AF258");

            entity.Property(e => e.Location_ID).HasDefaultValueSql("(newid())");
            entity.Property(e => e.ICreatedDateAndTime).HasDefaultValueSql("(getdate())");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<location> entity);
    }
}
