// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Shiva_Enterprise_APIs.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Shiva_Enterprise_APIs.Models.Configurations
{
    public partial class RoleMembershipConfiguration : IEntityTypeConfiguration<RoleMembership>
    {
        public void Configure(EntityTypeBuilder<RoleMembership> entity)
        {
            entity.HasKey(e => e.RoleMenmbershiID).HasName("PK__RoleMemb__37DF7DF41C67961E");

            entity.Property(e => e.RoleMenmbershiID).HasDefaultValueSql("(newid())");

            entity.HasOne(d => d.Role).WithMany(p => p.RoleMemberships).HasConstraintName("FK_RoleMembership_Role");

            entity.HasOne(d => d.User).WithMany(p => p.RoleMemberships).HasConstraintName("FK_RoleMembership_user");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RoleMembership> entity);
    }
}
