// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Shiva_Enterprise_APIs.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Shiva_Enterprise_APIs.Models.Configurations
{
    public partial class salesmanAgentConfiguration : IEntityTypeConfiguration<salesmanAgent>
    {
        public void Configure(EntityTypeBuilder<salesmanAgent> entity)
        {
            entity.HasKey(e => e.SalesmanAgentID).HasName("PK__salesman__B94AD674532DF6E8");

            entity.Property(e => e.SalesmanAgentID).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedDateAndTime).HasDefaultValueSql("(getdate())");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<salesmanAgent> entity);
    }
}
