// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Shiva_Enterprise_APIs.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Shiva_Enterprise_APIs.Models.Configurations
{
    public partial class stateConfiguration : IEntityTypeConfiguration<state>
    {
        public void Configure(EntityTypeBuilder<state> entity)
        {
            entity.HasKey(e => e.State_ID).HasName("PK__state__AF9338D7D97D88B7");

            entity.Property(e => e.State_ID).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedDateAndTime).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Country).WithMany(p => p.states).HasConstraintName("FK_state_Country");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<state> entity);
    }
}
